### ISSUE TITLE
reporting `could not parse static page content` errors in your hosted page https://nartc.me/blog

### ISSUE THREAD

**Issue by micalevisk** [nartc/tnc-scully#1]
Hi! sorry for bother you here but couple days ago I was reading the page `AutoMapper + Nestjs` but now I'm getting an error, thus I'm reporting it to you because your blog has great content

![page error](https://user-images.githubusercontent.com/13461315/114325443-31a1f380-9afe-11eb-806b-e5adecd5deaa.png)

```
Sorry, could not parse static page content

This might happen if you are not using the static generated pages.
```

Pages with this error are:

- https://nartc.me/blog/automapper-nestjs
- https://nartc.me/blog/angular-cli-tailwindcss
- https://nartc.me/blog/automapper-typescript-1
- https://nartc.me/blog/internalize-request-status-rxjs
- https://nartc.me/blog/customizing-angular-ui-library
- https://nartc.me/blog/add-utterances-comments-scully
- https://nartc.me/blog/nestjs-swagger-generics
- https://nartc.me/blog/angular-recaptcha-v2
- https://nartc.me/blog/angular-root-injector

---

I can read the `automapper-nestjs.md` file tho, thanks for made this repo public :p

**Comment by nartc** [comment]
I think this is fixed :P Thanks
