### ISSUE TITLE
RSS Feed

### ISSUE THREAD

**Issue by hakimio** [nartc/tnc-scully#2]
I would like to follow your blog on RSS feed reader but I can't find a link to your RSS feed. Can you add it?

**Comment by nartc** [comment]
@hakimio thanks for the kind words. Yes I can add a RSS feed

**Comment by nartc** [comment]
@hakimio Check out the latest version of https://nartc.me/ (you might have to wait to see my avatar glows rainbow to reload with the new version haha, or you can just empty cache and refresh). There will be a new RSS Feed link. Thanks again for the support
![image](https://user-images.githubusercontent.com/25516557/119160330-c3feb680-ba1d-11eb-9760-20112f81006d.png)

**Comment by hakimio** [comment]
@nartc Thanks :)
